INSERT INTO UNIDADES (NOME, LOCALIZACAO) VALUES ('Laboratório Pfizer', 'Bloco Principal');
INSERT INTO FUNCIONARIOS (TIPO_FUNCIONARIO, NOME, MATRICULA) VALUES ('RESPONSAVEL_ALMOXARIFADO', 'Dr. House', '99999');
INSERT INTO MATERIAIS (NOME, TIPO, QUANTIDADE_DISPONIVEL) VALUES ('AstraZeneca', 'REAGENTE', 30);