INSERT INTO UNIDADES (ID, NOME, LOCALIZACAO) VALUES (1, 'Laboratório Central', 'Bloco A');
INSERT INTO UNIDADES (ID, NOME, LOCALIZACAO) VALUES (2, 'UTI Neonatal', 'Bloco C, 2º Andar');

INSERT INTO FUNCIONARIOS (ID, TIPO_FUNCIONARIO, NOME, MATRICULA) VALUES (1, 'RESPONSAVEL_ALMOXARIFADO', 'João da Silva', '12345');
INSERT INTO FUNCIONARIOS (ID, TIPO_FUNCIONARIO, NOME, MATRICULA) VALUES (2, 'RESPONSAVEL_ALMOXARIFADO', 'Maria Oliveira', '67890');

INSERT INTO MATERIAIS (ID, NOME, TIPO, QUANTIDADE_DISPONIVEL) VALUES (1, 'Reagente Alfa', 'REAGENTE', 100);
INSERT INTO MATERIAIS (ID, NOME, TIPO, QUANTIDADE_DISPONIVEL) VALUES (2, 'Seringa Descartável 5ml', 'DESCARTAVEL', 500);
INSERT INTO MATERIAIS (ID, NOME, TIPO, QUANTIDADE_DISPONIVEL) VALUES (3, 'Monitor Cardíaco', 'EQUIPAMENTO', 15);